CXX-2580 fix change stream examples (#938)
* use mongocxx::pool

Will be necessary to insert documents in a separate thread.

* insert documents in a separate thread

use username: alice to satisfy $match stage in Example 4

* update examples

Repeat iteration until receiving the first document.
This currently infinitely loops due to no events being generated.

* use atomic store

fixes this error on g++7.5.0:
```
/home/ubuntu/code/mongo-cxx-driver-CXX2580/src/mongocxx/test/change_streams.cpp:448:43: error: use of deleted function 'std::atomic<bool>::atomic(const std::atomic<bool>&)'
     std::atomic_bool insert_thread_done = false;
                                           ^~~~~
```

* use string_view compare, not ==

fixes this error on g++7.5.0: `no match for 'operator=='`

* link to thread library in test_driver

* construct bsoncxx::document::value explicitly

Fixes VS2015 error:

C:\local\boost_1_60_0\boost/optional/optional.hpp(629): error C2664: 'void boost::optional_detail::optional_base<T>::assign_value(bsoncxx::v_noabi::document::value &&,boost::optional_detail::optional_base<T>::is_reference_tag)': cannot convert argument 1 from 'const bsoncxx::v_noabi::document::view' to 'const bsoncxx::v_noabi::document::value &' [C:\data\mci\61c6a13adf46b665b82425a7e8fac2db\mongo-cxx-driver\build\src\mongocxx\test\test_driver.vcxproj]

* Update src/mongocxx/test/change_streams.cpp

Co-authored-by: Roberto C. Sánchez <roberto@connexer.com>